### ISSUE TITLE
Add readable objects

### ISSUE THREAD

**Issue by mprysia** [Maroski/VRProject#17]
This would be a new type of interactable that would require the read ability. 

Ideas for features:
- If the player does not have the read ability the text will look scrambled
- The text should hover above the sign when the player interacts with it
- The text will close when the player looks away or if they click a second time (click on click off)

This is should be implemented ASAP as it will be an easy way to provide guidance should we fail to get narration up and running.

**Comment by Maroski** [comment]
Could we use the existing GuiOutput context message to satisfy this issue trivially? Or do you think a more involved graphic could be used (a book open to some set of pages that can be read)?
