### ISSUE TITLE
Improve the fireball mechanics

### ISSUE THREAD

**Issue by mprysia** [Maroski/VRProject#22]
Things we should figure out:
- Find a nice amount of time to propel the fireball before it explodes
- Find a nice distance to keep the shrine activated for
- Add a visual representation of the shrine's AoE
- Get the fireball to explode when it collides with any (collidable) object
- Add a firing rate timer and find a nice sweet spot to prevent spam shots and to minimize wait time when you miss
- Consider replacing the use of a force with the use of a custom update method to propel the fireball. To make it easier to fine tune acceleration for instance. Another option would be to make initial velocity/acceleration fields in the fireball object and to convert those into impulse force/continuous force values to be used when the fireball is fired/in it's update loop.

Some of these points will come down to fine tuning and may even change between shrines, but we should try to play test to get something that feels close to right.

**Comment by Maroski** [comment]
Not really even sure this shouldn't be tagged Priority - Low

**Comment by Maroski** [comment]
Will not be using fireball, or any projectiles.
