### ISSUE TITLE
Fix functionality of OnHover and OnHoverOff

### ISSUE THREAD

**Issue by mprysia** [Maroski/VRProject#9]
OnHover should take a time delta as a parameter to indicate how long the player has been hovering on the _same_ object.

OnHoverOff should be changed to OnChangeTarget. It should take a RaycastHit as a parameter and should be called when the object the player is looking at changes. The parameter should be nullable to indicate when the player is no longer looking at an object.

Currently OnHover is called every frame the player is looking at _any_ object which is not very useful information since we tend to care which type of object we are looking at.

**Comment by Maroski** [comment]
Merged as of #11
